@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle Hollow
actor Пользователь as User
rectangle Сервер {
  User --> (Запустить чистку)
  (Проверить наличие пятен) <. (Запустить чистку) : <<include>>
  (Определить положение пятен и Робота) .> (Проверить наличие пятен) : <<extend>>
  (Определить маршрут Робота) <. (Определить положение пятен и Робота) : <<include>>
  (Передать команды Роботу) <. (Определить маршрут Робота) : <<include>>
}
rectangle Робот {
  (Передать команды Роботу) ..> (Принять команды с сервера) : <<include>>
  (Принять команды с сервера) .> (Реализовать команды) : <<include>>
  (Реализовать команды) .> (Станцевать танец победы) : <<include>>
}
@enduml